version: '3.2'
services:
  datameta-app:
    image: "datameta/datameta:dev"
    environment:
      SQLALCHEMY_URL: postgresql://datameta:datameta@datameta-postgresql/datameta
      SESSION_URL: datameta-memcached:11211
      SESSION_KEY: datameta
      SESSION_SECRET:
      DATAMETA_STORAGE_PATH: /var/datameta/storage
      DATAMETA_DEMO_MODE: "false"
      DATAMETA_INITIAL_FULLNAME:
      DATAMETA_INITIAL_EMAIL:
      DATAMETA_INITIAL_PASS:
      DATAMETA_INITIAL_GROUPNAME:
      WAITRESS_MAX_REQUEST_BODY_SIZE: 10737418240 # 10 GB
      WAITRESS_LISTEN: "*:8080"
      WAITRESS_URL_SCHEME:
      WAITRESS_TRUSTED_PROXY_HEADERS:
      WAITRESS_TRUSTED_PROXY:
    volumes:
      - type: volume
        source: datameta-filestorage
        target: /var/datameta/storage
        volume:
          nocopy: true
    ports:
      - target: 8080
        published: 9950
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode : dnsrr
  datameta-memcached:
    image: "memcached:1.6.3"
    command: ['memcached', '-v', '-m', '3072', '-I', '50m']
    deploy:
      endpoint_mode : dnsrr
  datameta-postgresql:
    image: "postgres:13-alpine"
    volumes:
      - type: volume
        source: datameta-db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      POSTGRES_USER: datameta
      POSTGRES_PASSWORD: datameta
    command: ['postgres', '-c', 'work_mem=512MB']
    deploy:
      endpoint_mode : dnsrr

volumes:
  datameta-db:
    external: true
  datameta-filestorage:
    external: true
