"""add expiration for files

Revision ID: 4ac6c2e47767
Revises: 75b0775a8695
Create Date: 2021-03-03 15:24:48.426767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac6c2e47767'
down_revision = '75b0775a8695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('upload_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'upload_expires')
    # ### end Alembic commands ###
