"""add tfa_secret to passwordtokens

Revision ID: d77db77b23d8
Revises: 2c37dad5b9a2
Create Date: 2021-10-14 11:13:18.591637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77db77b23d8'
down_revision = '2c37dad5b9a2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwordtokens', sa.Column('tfa_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwordtokens', 'tfa_secret')
    # ### end Alembic commands ###
