"""add TfaToken

Revision ID: 7fcf7a444c6e
Revises: 2c37dad5b9a2
Create Date: 2021-10-18 17:51:27.497506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fcf7a444c6e'
down_revision = '2c37dad5b9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tfatokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('expires', sa.DateTime(), nullable=False),
        sa.Column('secret', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tfatokens_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tfatokens')),
        sa.UniqueConstraint('uuid', name=op.f('uq_tfatokens_uuid')),
        sa.UniqueConstraint('value', name=op.f('uq_tfatokens_value'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tfatokens')
    # ### end Alembic commands ###
