"""add metadata.long_description; rename metadata[lintmessage->short_description]

Revision ID: cfb9cf1b7f6c
Revises: 88224d713a42
Create Date: 2021-03-16 18:40:22.110519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb9cf1b7f6c'
down_revision = '88224d713a42'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('long_description', sa.Text(), nullable=True))
    op.alter_column('metadata', 'lintmessage', new_column_name='short_description')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metadata', 'short_description', new_column_name='lintmessage')
    op.drop_column('metadata', 'long_description')
    # ### end Alembic commands ###
