"""add 2fasecret to users

Revision ID: 2c37dad5b9a2
Revises: f6a70402119f
Create Date: 2021-08-13 16:40:03.175875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c37dad5b9a2'
down_revision = 'f6a70402119f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tfa_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tfa_secret')
    # ### end Alembic commands ###
