"""added file expiration notice

Revision ID: 07b01f31329a
Revises: d8f6811e4d92
Create Date: 2021-03-03 05:56:59.666619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b01f31329a'
down_revision = 'd8f6811e4d92'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'expires')
    # ### end Alembic commands ###
