"""add 2fa functionality

Revision ID: b5b86c536020
Revises: 98911b881230
Create Date: 2021-10-20 01:10:15.944795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5b86c536020'
down_revision = '98911b881230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tfatokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('expires', sa.DateTime(), nullable=False),
        sa.Column('secret', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tfatokens_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tfatokens')),
        sa.UniqueConstraint('uuid', name=op.f('uq_tfatokens_uuid')),
        sa.UniqueConstraint('value', name=op.f('uq_tfatokens_value'))
    )
    op.add_column('users', sa.Column('tfa_secret', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tfa_secret')
    op.drop_table('tfatokens')
    # ### end Alembic commands ###
