"""make group name unique

Revision ID: 16a09feb3391
Revises: cfb9cf1b7f6c
Create Date: 2021-03-25 20:59:08.171642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a09feb3391'
down_revision = 'cfb9cf1b7f6c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_groups_name'), 'groups', ['name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_groups_name'), 'groups', type_='unique')
    # ### end Alembic commands ###
