"""added msetreplacements table, moved update-related fields from mset

Revision ID: 2735e05ff276
Revises: 7fdc829db18d
Create Date: 2021-06-24 08:35:38.370074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2735e05ff276'
down_revision = '7fdc829db18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'msetreplacements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('datetime', sa.DateTime(), nullable=False),
        sa.Column('label', sa.String(length=140), nullable=False),
        sa.Column('new_metadataset_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['new_metadataset_id'], ['metadatasets.id'], name=op.f('fk_msetreplacements_new_metadataset_id_metadatasets')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_msetreplacements_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_msetreplacements')),
        sa.UniqueConstraint('uuid', name=op.f('uq_msetreplacements_uuid'))
    )
    op.add_column('metadatasets', sa.Column('replaced_via_event_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_metadatasets_replaced_by_id_metadatasets', 'metadatasets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_metadatasets_replaced_via_event_id_msetreplacements'), 'metadatasets', 'msetreplacements', ['replaced_via_event_id'], ['id'], use_alter=True)
    op.drop_column('metadatasets', 'replaced_by_id')
    op.drop_column('metadatasets', 'is_deprecated')
    op.drop_column('metadatasets', 'deprecated_label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadatasets', sa.Column('deprecated_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('metadatasets', sa.Column('is_deprecated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('metadatasets', sa.Column('replaced_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_metadatasets_replaced_via_event_id_msetreplacements'), 'metadatasets', type_='foreignkey')
    op.create_foreign_key('fk_metadatasets_replaced_by_id_metadatasets', 'metadatasets', 'metadatasets', ['replaced_by_id'], ['id'])
    op.drop_column('metadatasets', 'replaced_via_event_id')
    op.drop_table('msetreplacements')
    # ### end Alembic commands ###
