"""file.storage_uri nullable

Revision ID: 26c2f6af45ab
Revises: d8f6811e4d92
Create Date: 2021-03-02 23:46:59.938789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c2f6af45ab'
down_revision = 'd8f6811e4d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'storage_uri',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'storage_uri',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    # ### end Alembic commands ###
