"""add serviceexecutions.uuid

Revision ID: 7fdc829db18d
Revises: 0f5d0ddc1764
Create Date: 2021-05-19 17:20:21.186954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fdc829db18d'
down_revision = '0f5d0ddc1764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serviceexecutions', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(op.f('uq_serviceexecutions_uuid'), 'serviceexecutions', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_serviceexecutions_uuid'), 'serviceexecutions', type_='unique')
    op.drop_column('serviceexecutions', 'uuid')
    # ### end Alembic commands ###
