"""added replacement mset attributes

Revision ID: 2899e8fde16d
Revises: 6e77c5e9111b
Create Date: 2021-05-04 21:32:09.463914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2899e8fde16d'
down_revision = '6e77c5e9111b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadatasets', sa.Column('is_deprecated', sa.Boolean(), nullable=True))
    op.add_column('metadatasets', sa.Column('deprecated_label', sa.String(), nullable=True))
    op.add_column('metadatasets', sa.Column('replaced_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_metadatasets_replaced_by_id_metadatasets'), 'metadatasets', 'metadatasets', ['replaced_by_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_metadatasets_replaced_by_id_metadatasets'), 'metadatasets', type_='foreignkey')
    op.drop_column('metadatasets', 'replaced_by_id')
    op.drop_column('metadatasets', 'deprecated_label')
    op.drop_column('metadatasets', 'is_deprecated')
    # ### end Alembic commands ###
