"""add expiration for files

Revision ID: a88f7775f3ba
Revises: 75b0775a8695
Create Date: 2021-03-03 11:24:23.896382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88f7775f3ba'
down_revision = '75b0775a8695'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('expires', sa.DateTime(), nullable=True))
    op.alter_column('files', 'storage_uri',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'storage_uri',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.drop_column('files', 'expires')
    # ### end Alembic commands ###
