"""Update File Model

Revision ID: d8f6811e4d92
Revises: 0d88405b5538
Create Date: 2021-03-02 16:31:55.949772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f6811e4d92'
down_revision = '0d88405b5538'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content_uploaded', sa.Boolean(create_constraint=False), nullable=False))
    op.add_column('files', sa.Column('storage_uri', sa.String(length=2048), nullable=False))
    op.alter_column('files', 'filesize',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_files_storage_uri'), 'files', ['storage_uri'])
    op.drop_column('files', 'name_storage')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name_storage', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_files_storage_uri'), 'files', type_='unique')
    op.alter_column('files', 'filesize',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('files', 'storage_uri')
    op.drop_column('files', 'content_uploaded')
    # ### end Alembic commands ###
