"""files.filesize bigint

Revision ID: 75b0775a8695
Revises: 26c2f6af45ab
Create Date: 2021-03-03 00:08:00.895764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b0775a8695'
down_revision = '26c2f6af45ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'filesize',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_column('files', 'checksum_crypt')
    op.drop_column('files', 'filesize_crypt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filesize_crypt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('checksum_crypt', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('files', 'filesize',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
