"""added failed_login tracking

Revision ID: 98911b881230
Revises: 7fdc829db18d
Create Date: 2021-10-29 15:01:29.844727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98911b881230'
down_revision = '7fdc829db18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'loginattempts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loginattempts_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_loginattempts')),
        sa.UniqueConstraint('uuid', name=op.f('uq_loginattempts_uuid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loginattempts')
    # ### end Alembic commands ###
