"""make apikey.value unique

Revision ID: b0e4bfa7129b
Revises: 8399f5ae0845
Create Date: 2021-04-23 10:05:40.721355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e4bfa7129b'
down_revision = '8399f5ae0845'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_apikeys_value'), 'apikeys', ['value'])
    # ### end Alembic commands ###
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_apikeys_value'), 'apikeys', type_='unique')
    # ### end Alembic commands ###