"""added msetreplacements table, moved update-related fields from mset

Revision ID: 37ecf07b7838
Revises: 7fdc829db18d
Create Date: 2021-06-15 09:09:20.305816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37ecf07b7838'
down_revision = '7fdc829db18d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msetreplacements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=140), nullable=False),
    sa.Column('metadataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metadataset_id'], ['metadatasets.id'], name=op.f('fk_msetreplacements_metadataset_id_metadatasets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_msetreplacements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msetreplacements')),
    sa.UniqueConstraint('uuid', name=op.f('uq_msetreplacements_uuid'))
    )
    op.drop_constraint('fk_metadatasets_replaced_by_id_metadatasets', 'metadatasets', type_='foreignkey')
    op.drop_column('metadatasets', 'deprecated_label')
    op.drop_column('metadatasets', 'is_deprecated')
    op.drop_column('metadatasets', 'replaced_by_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadatasets', sa.Column('replaced_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metadatasets', sa.Column('is_deprecated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('metadatasets', sa.Column('deprecated_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_metadatasets_replaced_by_id_metadatasets', 'metadatasets', 'metadatasets', ['replaced_by_id'], ['id'])
    op.drop_table('msetreplacements')
    # ### end Alembic commands ###
