"""add new field users.site_read

Revision ID: 68a28d6ed9cb
Revises: b0e4bfa7129b
Create Date: 2021-04-20 22:46:36.169743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a28d6ed9cb'
down_revision = 'b0e4bfa7129b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('site_read', sa.Boolean(create_constraint=False), nullable=True))
    op.execute('UPDATE users SET site_read = site_admin;')
    op.alter_column('users', 'site_read', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'site_read')
    # ### end Alembic commands ###
