"""added replacement metadataset attributes

Revision ID: 50c6d4c04883
Revises: 6e77c5e9111b
Create Date: 2021-05-04 16:31:57.693868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c6d4c04883'
down_revision = '6e77c5e9111b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadatasets', sa.Column('is_deprecated', sa.Boolean(), nullable=True))
    op.add_column('metadatasets', sa.Column('deprecated_label', sa.String(), nullable=True))
    op.add_column('metadatasets', sa.Column('replaced_by', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_metadatasets_replaced_by_metadatasets'), 'metadatasets', 'metadatasets', ['replaced_by'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_metadatasets_replaced_by_metadatasets'), 'metadatasets', type_='foreignkey')
    op.drop_column('metadatasets', 'replaced_by')
    op.drop_column('metadatasets', 'deprecated_label')
    op.drop_column('metadatasets', 'is_deprecated')
    # ### end Alembic commands ###
