"""make group name unique

Revision ID: 8399f5ae0845
Revises: 7b16156a6bca
Create Date: 2021-04-16 12:32:21.434583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8399f5ae0845'
down_revision = '7b16156a6bca'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_groups_name'), 'groups', ['name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_groups_name'), 'groups', type_='unique')
    # ### end Alembic commands ###
