"""Renamed ServiceExecution Table, fixed typo and added unique contraint

Revision ID: 0f5d0ddc1764
Revises: 6e77c5e9111b
Create Date: 2021-05-05 13:13:23.435768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f5d0ddc1764'
down_revision = '6e77c5e9111b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('serviceecexution', 'serviceexecution')
    op.create_unique_constraint(op.f('uq_services_name'), 'services', ['name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_services_name'), 'services', type_='unique')
    op.rename_table('serviceexecution', 'serviceecexution')
    # ### end Alembic commands ###
