"""added tracking of used passwords

Revision ID: 6a9f0bec38e6
Revises: 7fdc829db18d
Create Date: 2021-10-29 11:22:19.194633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9f0bec38e6'
down_revision = '7fdc829db18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usedpasswords',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usedpasswords_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_usedpasswords')),
        sa.UniqueConstraint('value', name=op.f('uq_usedpasswords_value'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usedpasswords')
    # ### end Alembic commands ###
