def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('root', '/')
    config.add_route('login', '/login')
    config.add_route('home', '/home')
    config.add_route('submit', '/submit')
    config.add_route('submit_data', '/submit/data')
    config.add_route('submit_samplesheet', '/submit/samplesheet')
    config.add_route('account', '/account')
    config.add_route('view', '/view')
    config.add_route('pending_unannotated', '/pending/unannotated.json')
    config.add_route('pending_annotated', '/pending/annotated.json')
    config.add_route('admin', '/admin')
    config.add_route('admin_json', '/admin.json')
