def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('root', '/')
    config.add_route('login', '/login')
    config.add_route('register', '/register')
    config.add_route('home', '/home')
    config.add_route('submit', '/submit')
    config.add_route('submit_action', '/submit/action')
    config.add_route('account', '/account')
    config.add_route('view', '/view')
    config.add_route('v_submit_view_json', '/submit/view.json')
    config.add_route('admin', '/admin')
    config.add_route('admin_json', '/admin.json')
