#!/bin/sh
# Copyright (c) 2021 Universität Tübingen, Germany
# Authors: Leon Kuchenbecker <leon.kuchenbecker@uni-tuebingen.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -x
set -e

# Replace environment variables with their respective values
TMP_DIR=$(mktemp -d)
echo "Executing in temp dir: ${TMP_DIR}"
cd "${TMP_DIR}"
cp -rT /workspace "${TMP_DIR}"

# Replace environment variables with their respective values
envsubst < "/workspace/conf/docker_development.ini" > "${TMP_DIR}/config.ini"


# Try to connect to the database, fail startup otherwise
psql -c '\dt' "$SQLALCHEMY_URL"

# Check if the database has been initialized and if not initialize it
if ! psql -c '\dt' "$SQLALCHEMY_URL" | fgrep alembic &>/dev/null; then
	alembic -c "${TMP_DIR}/config.ini" upgrade head
	alembic -c "${TMP_DIR}/config.ini" revision --autogenerate -m "init"
	alembic -c "${TMP_DIR}/config.ini" upgrade head
	initialize_datameta_db "${TMP_DIR}/config.ini"
fi

# Launch the application
pserve "${TMP_DIR}/config.ini"
