#!/bin/sh
# Copyright (c) 2021 Universität Tübingen, Germany
# Authors: Leon Kuchenbecker <leon.kuchenbecker@uni-tuebingen.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -x
set -e

# Replace environment variables with their respective values
envsubst < /docker_production.ini > /tmp/config.ini

# Try to connect to the database, fail startup otherwise
psql -c '\dt' "$SQLALCHEMY_URL"

# Check if the database has been initialized and if not initialize it
cd /tmp/datameta.src/
alembic -c /tmp/config.ini upgrade head
initialize_datameta_db -c /tmp/config.ini \
	--initial-user-fullname "$DATAMETA_INITIAL_FULLNAME" \
	--initial-user-email "$DATAMETA_INITIAL_EMAIL" \
	--initial-user-pass "$DATAMETA_INITIAL_PASS" \
	--initial-group "$DATAMETA_INITIAL_GROUPNAME" \
	--initial-api-key $DATAMETA_INITIAL_API_KEY
cd /

# Launch the application
pserve /tmp/config.ini
