version: '3.2'
services:
  datameta-app:
    image: "datameta/datameta:dev"
    environment:
      SQLALCHEMY_URL: postgresql://datameta:datameta@datameta-postgresql/datameta
      SESSION_URL: datameta-memcached:11211
      SESSION_KEY: datameta
      SESSION_SECRET: # Set a 64 character random string here
      DATAMETA_STORAGE_PATH: /var/datameta/storage
      DATAMETA_DEMO_MODE: "true"
      DATAMETA_INITIAL_FULLNAME:
      DATAMETA_INITIAL_EMAIL:
      DATAMETA_INITIAL_PASS:
      DATAMETA_INITIAL_GROUPNAME:
      # The maximum number of days an API key can be valid
      DATAMETA_API_KEYS_MAX_EXPIRE_DAYS: 365

      LETSENCRYPT_HOST:   # Picked up by nginx-proxy / letsencrypt. Comma separated list of hostnames.
      VIRTUAL_HOST:       # Picked up by nginx-proxy / letsencrypt. Comma separated list of hostnames. Every hostname in LETSENCRYPT_HOST must appear also here, otherwise cert acquisition will fail
      WAITRESS_MAX_REQUEST_BODY_SIZE: 10737418240 # 10 GB
      WAITRESS_LISTEN: "*:8080"
      WAITRESS_URL_SCHEME: "https"
      WAITRESS_TRUSTED_PROXY_HEADERS: "x-forwarded-for x-forwarded-host x-forwarded-proto x-forwarded-port"
      WAITRESS_TRUSTED_PROXY: "reverse-proxy"
    depends_on:
      - reverse-proxy
    volumes:
      - type: volume
        source: datameta-filestorage
        target: /var/datameta/storage
        volume:
          nocopy: true
    networks:
      - "net"
      - "cogdat"
    ports:
      - "8080" # Make containerized service available on port 8080 to any other container on a shared bridge network

  datameta-memcached:
    image: "memcached:1.6.3"
    command: ['memcached', '-v', '-m', '3072', '-I', '50m']
    deploy:
      endpoint_mode : dnsrr
    networks:
      - "cogdat"

  datameta-postgresql:
    image: "postgres:13-alpine"
    volumes:
      - type: volume
        source: datameta-db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      POSTGRES_USER: datameta
      POSTGRES_PASSWORD: datameta
    command: ['postgres', '-c', 'work_mem=512MB']
    deploy:
      endpoint_mode : dnsrr
    networks:
      - "cogdat"

  reverse-proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "reverse-proxy"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks:
      - "net"
    ports:
      - "80:80"
      - "443:443"

  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/acme.sh"
    depends_on:
      - "reverse-proxy"
    environment:
      NGINX_PROXY_CONTAINER: "reverse-proxy"
      NGINX_DOCKER_GEN_CONTAINER: "reverse-proxy"
      DEFAULT_EMAIL:
    restart: "always"
    networks:
      - "net"

volumes:
  datameta-db:
    external: true
  datameta-filestorage:
    external: true
  certs:
    external: true
  html:
    external: true
  vhost:
    external: true
  dhparam:
    external: true

# Setting external to false for networks means Docker will look for an existing network rather than making a throwaway
# one when you run `docker-compose up [args]`. Run `docker network create <network name>` to create the network if it
# doesn't already exist on the local docker engine.
networks:
  net:
    external: false
  cogdat:
    external: false
