name: Add latest tag to new release
on:
  release:
    types: [published] # This makes it run only when a new released is published

jobs:
  run:
    name: Add/update tag to new release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Run latest-tag
      uses: EndBug/latest-tag@6d22a6738f5c33059e3a8c6ca5dcf8eaf8a14599
      with:
        description: Latest releases version
        tag-name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
