name: PyPI

on: workflow_dispatch
  #release:
  #  types: [published]

jobs:
  pypi-publish:
    name: Publish tagged release on PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Verify Package Version vs Tag Version
      run: |
        pkg_ver="$(python setup.py -V)"
        tag_ver="${GITHUB_REF##*/}"
        tag_ver="v1.1.0"
        echo "Package version is $pkg_ver" >&2
        echo "Tag version is $tag_ver" >&2
        if [ "v$pkg_ver" != "$tag_ver" ]; then
          echo "Package version and tag name mismatch." >&2
          exit 1
        fi
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Create timestamp
      run: echo timestamp=$(date +%s) >> $GITHUB_ENV
    - name: Publish distribution package to PyPI (test)
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution package to PyPI (production)
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
