name: Run unit tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmemcached-dev
    - name: Set conda package directory
      run: |
        mkdir /tmp/condapkgs
        echo "CONDA_PKGS_DIRS=/tmp/condapkgs" >> $GITHUB_ENV
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        $CONDA/bin/conda create -p /tmp/condaenv python==${{ matrix.python-version }}'.*'
    - name: Activate conda environment
      run: |
        echo "/tmp/condaenv/bin" >> $GITHUB_PATH
        export PATH="/tmp/condaenv/bin:$PATH"
    - name: Install datameta
      run: |
        pip install ".[testing]"
    - name: Initialize Database
      run: |
        alembic -c ./conf/ci.ini revision --autogenerate -m "init"
        alembic -c ./conf/ci.ini upgrade head
    - name: Load default data
      run: |
        initialize_datameta_db ./conf/ci.ini
    - name: Run tests
      run: pytest
