name: Run unit tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.platform }}

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: datameta
          POSTGRES_PASSWORD: datameta
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      memcached:
        # Docker Hub image
        image: memcached
        ports:
          # Maps tcp port 11211 on service container to the host
          - 11211:11211

    env:
      SQLALCHEMY_TEST_URL: postgresql://datameta:datameta@localhost/test
      SESSION_URL: "localhost:11211"

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmemcached-dev
    - name: Set conda package directory
      run: |
        mkdir /tmp/condapkgs
        echo "CONDA_PKGS_DIRS=/tmp/condapkgs" >> $GITHUB_ENV
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        $CONDA/bin/conda create -p /tmp/condaenv python==${{ matrix.python-version }}'.*'
    - name: Activate conda environment
      run: |
        echo "/tmp/condaenv/bin" >> $GITHUB_PATH
        export PATH="/tmp/condaenv/bin:$PATH"
    - name: Install datameta
      run: |
        pip install ".[testing]"
    - name: List packagers
      run: |
        pip list
    - name: Run tests
      run: pytest .
